window.help_translations = {
    help: {
        tools: {
            pen: "Guía de la herramienta Pluma:\n1. Tipos de pluma: Normal, Lápiz (granulado), Bolígrafo (presión), Estilográfica (caligrafía) o Pincel (tinta).\n2. Color: 8 preajustes disponibles. Haga clic en el icono de más para un selector de color personalizado.\n3. Tamaño: Ajuste el ancho del trazo (1-50px) usando el control deslizante.\n4. Consejo: Mantenga pulsada la tecla Shift para dibujar líneas rectas.",
            shape: "Guía de la herramienta Forma:\n1. Formas: Línea, Rectángulo, Círculo, Elipse, Flecha, Flecha doble.\n2. Cómo dibujar: Presione y arrastre, luego suelte para terminar.\n3. Tamaño de flecha: Ajuste el tamaño de la punta de flecha independientemente (limitado a al menos el grosor de la línea).\n4. Estilo: Las formas usan la configuración actual de color y grosor de la pluma.",
            eraser: "Guía de la herramienta Borrador:\n1. Forma: Elija entre borrador circular o cuadrado.\n2. Tamaño: Ajuste el tamaño del borrador usando el control deslizante.\n3. Borrar todo: Use el botón 'Borrar' en la barra de herramientas para borrar todo el lienzo.",
        },
        background: "Guía de configuración de fondo:\n1. Color: Elija el color de fondo del lienzo.\n2. Patrones: Cuadrículas, Líneas, Pentagrama, Sistema de coordenadas, etc.\n3. Imagen: Cargue una imagen local como fondo. Soporta mover, redimensionar, rotar y voltear.\n4. Coordenadas: Cuando se selecciona el patrón de Coordenadas, haga clic en 'Mover origen' para arrastrar el punto de origen en el lienzo.",
        features: {
            timer: "Guía del Temporizador:\n1. Modos: Cronómetro y Cuenta regresiva.\n2. Configurar tiempo: Ingrese horas, minutos y segundos para la cuenta regresiva.\n3. Sonido: Habilite el sonido de finalización. Soporta carga de audio personalizado.\n4. Bucle: Establezca el número de repeticiones del sonido.\n5. Pantalla completa: Vea el temporizador en modo de pantalla completa.\n6. Modo mínimo: Haga doble clic en la visualización del tiempo para cambiar a vista mínima.",
            randomPicker: "Guía del Selector aleatorio:\n1. Importar nombres:\n   - Manual: Escriba nombres, uno por línea.\n   - Importar Excel: Haga clic en 'Importar' en la configuración, seleccione un archivo Excel/CSV. Lee automáticamente la columna 'Nombre' (personalizable).\n2. Modos: Seleccionar por Nombre o Número.\n3. Repetición: Habilite 'Permitir repeticiones' para permitir seleccionar el mismo nombre varias veces.",
            scoreboard: "Guía del Marcador:\n1. Agregar equipo: Haga clic para agregar una nueva columna de puntuación.\n2. Ajustar puntuación: Haga clic en los botones '+' o '-'.\n3. Editar nombre: Haga doble clic en el nombre del equipo para editar.\n4. Restablecer: Restablece todas las puntuaciones a cero pero mantiene los equipos.",
            teachingTools: "Guía de Herramientas didácticas:\n1. Tipos de herramientas: Regla (2 estilos) y Escuadra (tipos 60° y 45°).\n2. Agregar herramientas: Establezca la cantidad en la sección 'Agregar nuevo' y haga clic en 'Confirmar' para agregar al lienzo.\n3. Mover herramientas: Haga clic simple y arrastre para mover la posición de la herramienta.\n4. Ajustar herramientas: Haga doble clic para mostrar los puntos de control para rotar, redimensionar y eliminar.\n5. Dibujo en bordes: Dibujar cerca de los bordes de la herramienta ajustará el trazo al borde.\n6. Instancias múltiples: Puede colocar múltiples herramientas en el lienzo simultáneamente.",
            timeDisplay: "Guía de configuración de visualización de hora:\n1. Opciones de visualización: Elija mostrar fecha, hora o ambas.\n2. Zona horaria: Soporta las principales zonas horarias globales con ajuste automático de horario de verano.\n3. Formato: Formato de hora 12/24 horas, múltiples formatos de fecha disponibles.\n4. Estilo: Personalice el color de fuente, color de fondo y opacidad.\n5. Modo de pantalla completa: Clic simple o doble clic para entrar en la visualización de hora en pantalla completa.\n6. Arrastrar para mover: El widget de visualización de hora se puede arrastrar libremente a cualquier posición."
        }
    },
    common: {
        help: "Ayuda"
    }
};
