window.help_translations = {
    help: {
        tools: {
            pen: "Guide de l'outil Stylo :\n1. Types de stylo : Normal, Crayon (granuleux), Stylo bille (pression), Plume (calligraphie), ou Pinceau (encre).\n2. Couleur : 8 préréglages disponibles. Cliquez sur l'icône plus pour un sélecteur de couleur personnalisé.\n3. Taille : Ajustez la largeur du trait (1-50px) avec le curseur.\n4. Astuce : Maintenez la touche Shift pour tracer des lignes droites.",
            shape: "Guide de l'outil Forme :\n1. Formes : Ligne, Rectangle, Cercle, Ellipse, Flèche, Double flèche.\n2. Comment dessiner : Appuyez et faites glisser, puis relâchez pour terminer.\n3. Taille de la flèche : Ajustez la taille de la pointe de flèche indépendamment (limitée à au moins l'épaisseur de la ligne).\n4. Style : Les formes utilisent les paramètres de couleur et d'épaisseur actuels du stylo.",
            eraser: "Guide de l'outil Gomme :\n1. Forme : Choisissez entre une gomme circulaire ou carrée.\n2. Taille : Ajustez la taille de la gomme avec le curseur.\n3. Tout effacer : Utilisez le bouton 'Effacer' de la barre d'outils pour effacer tout le canevas.",
        },
        background: "Guide des paramètres d'arrière-plan :\n1. Couleur : Choisissez la couleur d'arrière-plan du canevas.\n2. Motifs : Grilles, Lignes, Portée musicale, Système de coordonnées, etc.\n3. Image : Téléchargez une image locale comme arrière-plan. Prend en charge le déplacement, le redimensionnement, la rotation et le retournement.\n4. Coordonnées : Lorsque le motif Coordonnées est sélectionné, cliquez sur 'Déplacer l'origine' pour faire glisser le point d'origine sur le canevas.",
        features: {
            timer: "Guide du Minuteur :\n1. Modes : Chronomètre et Compte à rebours.\n2. Réglage du temps : Entrez les heures, minutes et secondes pour le compte à rebours.\n3. Son : Activez le son de fin. Prend en charge le téléchargement audio personnalisé.\n4. Boucle : Définissez le nombre de répétitions du son.\n5. Plein écran : Affichez le minuteur en mode plein écran.\n6. Mode minimal : Double-cliquez sur l'affichage du temps pour basculer vers la vue minimale.",
            randomPicker: "Guide du Sélecteur aléatoire :\n1. Importer des noms :\n   - Manuel : Tapez les noms, un par ligne.\n   - Import Excel : Cliquez sur 'Importer' dans les paramètres, sélectionnez un fichier Excel/CSV. Lecture automatique de la colonne 'Nom' (personnalisable).\n2. Modes : Sélection par Nom ou Numéro.\n3. Répétition : Activez 'Autoriser les répétitions' pour permettre de sélectionner le même nom plusieurs fois.",
            scoreboard: "Guide du Tableau de scores :\n1. Ajouter une équipe : Cliquez pour ajouter une nouvelle colonne de score.\n2. Ajuster le score : Cliquez sur les boutons '+' ou '-'.\n3. Modifier le nom : Double-cliquez sur le nom de l'équipe pour le modifier.\n4. Réinitialiser : Remet tous les scores à zéro mais conserve les équipes.",
            teachingTools: "Guide des Outils pédagogiques :\n1. Types d'outils : Règle (2 styles) et Équerre (types 60° et 45°).\n2. Ajouter des outils : Définissez la quantité dans la section 'Ajouter nouveau' et cliquez sur 'Confirmer' pour ajouter au canevas.\n3. Déplacer les outils : Simple-cliquez et faites glisser pour déplacer la position de l'outil.\n4. Ajuster les outils : Double-cliquez pour afficher les points de contrôle pour la rotation, le redimensionnement et la suppression.\n5. Dessin sur les bords : Le dessin près des bords de l'outil accrochera le trait au bord.\n6. Instances multiples : Vous pouvez placer plusieurs outils sur le canevas simultanément.",
            timeDisplay: "Guide des Paramètres d'affichage de l'heure :\n1. Options d'affichage : Choisissez d'afficher la date, l'heure ou les deux.\n2. Fuseau horaire : Prend en charge les principaux fuseaux horaires mondiaux avec ajustement automatique de l'heure d'été.\n3. Format : Format horaire 12/24 heures, plusieurs formats de date disponibles.\n4. Style : Personnalisez la couleur de la police, la couleur d'arrière-plan et l'opacité.\n5. Mode plein écran : Simple-clic ou double-clic pour entrer en affichage plein écran de l'heure.\n6. Glisser pour déplacer : Le widget d'affichage de l'heure peut être librement déplacé à n'importe quelle position."
        }
    },
    common: {
        help: "Aide"
    }
};
